"""extend transplant centres for NOTTO provenance

Revision ID: 3e02782109fe
Revises: cbbad0d8c9a7
Create Date: 2026-09-30 17:41:42.064871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e02782109fe'
down_revision: Union[str, None] = 'cbbad0d8c9a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transplant_centres', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('transplant_centres', sa.Column('district', sa.String(length=100), nullable=True))
    op.add_column('transplant_centres', sa.Column('registration_type', sa.String(length=100), nullable=True))
    op.add_column('transplant_centres', sa.Column('raw_organ_tissue_type', sa.Text(), nullable=True))
    op.add_column('transplant_centres', sa.Column('details', sa.Text(), nullable=True))
    op.add_column('transplant_centres', sa.Column('website', sa.String(length=500), nullable=True))
    op.add_column('transplant_centres', sa.Column('source_record_id', sa.Integer(), nullable=True))
    op.add_column('transplant_centres', sa.Column('source_dataset_version', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transplant_centres', 'source_dataset_version')
    op.drop_column('transplant_centres', 'source_record_id')
    op.drop_column('transplant_centres', 'website')
    op.drop_column('transplant_centres', 'details')
    op.drop_column('transplant_centres', 'raw_organ_tissue_type')
    op.drop_column('transplant_centres', 'registration_type')
    op.drop_column('transplant_centres', 'district')
    op.drop_column('transplant_centres', 'address')
    # ### end Alembic commands ###
