"""add unique constraint for NOTTO source records

Revision ID: b51bcf843407
Revises: 3e02782109fe
Create Date: 2026-09-30 18:03:57.698406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b51bcf843407'
down_revision: Union[str, None] = '3e02782109fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'transplant_centres', ['source_record_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transplant_centres', type_='unique')
    # ### end Alembic commands ###
