"""phase 2 case status and transplant type enums

Revision ID: cbbad0d8c9a7
Revises: e3633c83227c
Create Date: 2026-09-21 15:31:32.977169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbbad0d8c9a7'
down_revision: Union[str, None] = 'e3633c83227c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_case_status_history_case_id'), 'case_status_history', ['case_id'], unique=False)
    op.create_index(op.f('ix_patient_preferences_case_id'), 'patient_preferences', ['case_id'], unique=False)
    # (transplant_type enum handled manually below — autogenerate's alter_column
    # does not create the Postgres enum type itself, it must exist first)
    op.create_index(op.f('ix_transplant_cases_patient_id'), 'transplant_cases', ['patient_id'], unique=False)
    op.create_index(op.f('ix_transplant_cases_status'), 'transplant_cases', ['status'], unique=False)
    # ### end Alembic commands ###

    # --- Manual: transplant_type VARCHAR -> Postgres ENUM ---
    op.execute("CREATE TYPE transplant_type AS ENUM ('KIDNEY','LIVER','HEART','LUNG','CORNEAL','BONE_MARROW')")
    op.execute("ALTER TABLE transplant_cases ALTER COLUMN transplant_type TYPE transplant_type USING transplant_type::transplant_type")

    # --- Manual addition (autogenerate cannot see enum VALUE changes on an
    # existing Postgres enum type — only column type changes) ---
    # Phase 1 shipped `case_status` with a 10-value draft lifecycle. Phase 2
    # replaces it with the approved 7-value lifecycle. This is a fresh dev
    # database with no real case data, so we do a clean swap: cast the column
    # to text, map any old value with no direct equivalent to NEW, then cast
    # to a freshly created enum type.
    op.execute("ALTER TABLE transplant_cases ALTER COLUMN status TYPE text")
    op.execute("""
        UPDATE transplant_cases
        SET status = 'NEW'
        WHERE status NOT IN ('NEW','DOCUMENT_COLLECTION','UNDER_REVIEW','COORDINATOR_REVIEW','CENTRE_REVIEW','COMPLETED','CANCELLED')
    """)
    op.execute("DROP TYPE case_status")
    op.execute("""
        CREATE TYPE case_status AS ENUM (
            'NEW','DOCUMENT_COLLECTION','UNDER_REVIEW','COORDINATOR_REVIEW','CENTRE_REVIEW','COMPLETED','CANCELLED'
        )
    """)
    op.execute("ALTER TABLE transplant_cases ALTER COLUMN status TYPE case_status USING status::case_status")
    op.execute("ALTER TABLE transplant_cases ALTER COLUMN status SET DEFAULT 'NEW'")


def downgrade() -> None:
    # Best-effort reverse of the manual enum swap above.
    op.execute("ALTER TABLE transplant_cases ALTER COLUMN status TYPE text")
    op.execute("DROP TYPE case_status")
    op.execute("""
        CREATE TYPE case_status AS ENUM (
            'DRAFT','SUBMITTED','AI_RECOMMENDATION_READY','DOCUMENT_REVIEW','COORDINATOR_REVIEW',
            'CENTRE_REVIEW','ADDITIONAL_DOCUMENTS_REQUIRED','IN_PROGRESS','COMPLETED','CLOSED'
        )
    """)
    op.execute("UPDATE transplant_cases SET status = 'DRAFT' WHERE status NOT IN ('COORDINATOR_REVIEW','CENTRE_REVIEW','COMPLETED')")
    op.execute("ALTER TABLE transplant_cases ALTER COLUMN status TYPE case_status USING status::case_status")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transplant_cases_status'), table_name='transplant_cases')
    op.drop_index(op.f('ix_transplant_cases_patient_id'), table_name='transplant_cases')
    op.execute("ALTER TABLE transplant_cases ALTER COLUMN transplant_type TYPE VARCHAR(100) USING transplant_type::text")
    op.execute("DROP TYPE transplant_type")
    op.drop_index(op.f('ix_patient_preferences_case_id'), table_name='patient_preferences')
    op.drop_index(op.f('ix_case_status_history_case_id'), table_name='case_status_history')
    # ### end Alembic commands ###
